# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test (rails ${{ matrix.rails_version }} / ruby ${{ matrix.ruby }} ${{ matrix.additional_name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # BLACKLIGHT 7, only test with esbuild

          - rails_version: "7.2.1"
            ruby: "3.3"
            additional_engine_cart_rails_options: "--javascript=esbuild"
            additional_name: "/ esbuild, sprockets"

          - rails_version: "7.1.4"
            ruby: "3.2"
            additional_engine_cart_rails_options: "--javascript=esbuild"
            additional_name: "/ esbuild, sprockets"

          - rails_version: "7.0.8.4"
            ruby: "3.1"
            additional_engine_cart_rails_options: "--javascript=esbuild"
            additional_name: "/ esbuild, sprockets"



    env:
      BLACKLIGHT_VERSION: "~> 7.0" # only test on BL 7 for now
      RAILS_VERSION: ${{ matrix.rails_version }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: "latest"
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake ci
